package com.devicescope.app.data

import android.content.Context
import java.util.Locale

object ReportBuilder {

    fun build(context: Context): String = runCatching {
        buildReport(context)
    }.getOrDefault("DeviceScope report (error)")

    private fun buildReport(context: Context): String {
        val overview = SystemInfoProvider.collect(context)
        val cpu = CpuInfoProvider.collect()
        val memory = MemoryProvider.collect(context)
        val battery = BatteryProvider.collect(context)
        val display = DisplayProvider.collect(context)
        val network = NetworkProvider.collect(context)
        val apps = AppsProvider.collect(context)
        val sensors = SensorProvider.collect(context)
        val cameras = CameraProvider.collect(context)
        return linesOf(overview, cpu, memory, battery, display, network, apps, sensors, cameras).joinToString("\n")
    }

    private fun linesOf(
        overview: OverviewInfo,
        cpu: CpuInfo,
        memory: MemoryInfo,
        battery: BatteryInfo,
        display: DisplayInfo,
        network: NetworkInfo,
        apps: List<AppEntry>,
        sensors: List<SensorEntry>,
        cameras: List<CameraEntry>
    ): List<String> = listOf(
        "DeviceScope report",
        deviceLine(overview),
        "Android: ${overview.androidVersion}",
        "SoC: ${overview.soc.ifBlank { "Unknown" }}",
        "CPU: ${cpu.cores} cores, max ${cpu.maxFreqMhz} MHz",
        "RAM: ${memory.ramUsedMb}/${memory.ramTotalMb} MB",
        storageLine(memory),
        batteryLine(battery),
        "Display: ${display.resolution} @ ${display.refreshRateHz} Hz",
        networkLine(network),
        "Apps: ${apps.size} installed",
        "Sensors: ${sensors.size}",
        "Cameras: ${cameras.size}",
        "— generated by DeviceScope"
    )

    private fun deviceLine(overview: OverviewInfo): String {
        val model = overview.model.ifBlank { "Unknown" }
        val manufacturer = overview.manufacturer.ifBlank { "Unknown" }
        return "Device: $model ($manufacturer)"
    }

    private fun storageLine(memory: MemoryInfo): String {
        val freeGb = memory.storageFreeBytes / 1_000_000_000.0
        return "Storage free: ${String.format(Locale.US, "%.1f", freeGb)} GB"
    }

    private fun batteryLine(battery: BatteryInfo): String {
        val temp = String.format(Locale.US, "%.1f", battery.tempC)
        return "Battery: ${battery.levelPct}%, $temp C, charging: ${battery.isCharging}"
    }

    private fun networkLine(network: NetworkInfo): String {
        val operator = network.operatorName.ifBlank { "Unknown" }
        return "Network: $operator ${network.networkType} (signal ${network.signalStrengthDbm} dBm)"
    }
}